// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BottomInfo: typeof import('./components/button/BottomInfo.vue')['default']
    CodeButton: typeof import('./components/button/CodeButton.vue')['default']
    Collapse: typeof import('./components/button/Collapse.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOverlay: typeof import('element-plus/es')['ElOverlay']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    FixedDialog: typeof import('./components/dialog/FixedDialog.vue')['default']
    FixedLoading: typeof import('./components/dialog/FixedLoading.vue')['default']
    Footer: typeof import('./components/footer/footer.vue')['default']
    MobileFooter: typeof import('./components/mobileFooter/mobileFooter.vue')['default']
    NavigationBar: typeof import('./components/navigationBar/navigationBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SgIconTitle: typeof import('./components/title/sgIconTitle.vue')['default']
    SgLayoutBox: typeof import('./components/layout/sgLayoutBox.vue')['default']
    SgLayoutCenter: typeof import('./components/layout/sgLayoutCenter.vue')['default']
    SgLayoutContainer: typeof import('./components/layout/sgLayoutContainer.vue')['default']
    SgLayoutFlex: typeof import('./components/layout/sgLayoutFlex.vue')['default']
    SgLayoutFlexAverage: typeof import('./components/layout/sgLayoutFlexAverage.vue')['default']
    SgLayoutScroll: typeof import('./components/layout/sgLayoutScroll.vue')['default']
    SgTitle: typeof import('./components/title/sgTitle.vue')['default']
  }
}
